version: '3.12'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: >
      sh -c "rm -f voting.db && python createdb.py && python app.py"